import { GoogleGenAI } from '@google/genai';
import 'dotenv/config';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

function buildContents(question) {
	if (typeof question === 'string') {
		return question;
	}

	if (Array.isArray(question) && question.length > 0) {
		return question.map((msg) => ({
			role: msg.role === 'bot' ? 'model' : 'user',
			parts: [{ text: msg.text ?? '' }],
		}));
	}

	throw new Error(
		'Question must be a string or a non-empty array of chat messages.'
	);
}

async function askQuestion(question) {
	if (!GEMINI_API_KEY) {
		throw new Error('Missing GEMINI_API_KEY in environment variables.');
	}

	const response = await ai.models.generateContent({
		model: 'gemini-3.5-flash',
		contents: buildContents(question),
	});

	return response.text ?? 'No response generated by Gemini.';
}

export { askQuestion };
